// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQjJgUJoAOOJYPyg7II746V6lr50MHsEs',
    appId: '1:261846872293:web:40b3cf6b8ea20a8ba7e40c',
    messagingSenderId: '261846872293',
    projectId: 'fuji-clinic-management-app',
    authDomain: 'fuji-clinic-management-app.firebaseapp.com',
    storageBucket: 'fuji-clinic-management-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmKlc8WjqOuTXrwEg20b5ZELPHW_5zmhw',
    appId: '1:261846872293:android:134251d5fca904fea7e40c',
    messagingSenderId: '261846872293',
    projectId: 'fuji-clinic-management-app',
    storageBucket: 'fuji-clinic-management-app.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQjJgUJoAOOJYPyg7II746V6lr50MHsEs',
    appId: '1:261846872293:web:219fc69c3b399e19a7e40c',
    messagingSenderId: '261846872293',
    projectId: 'fuji-clinic-management-app',
    authDomain: 'fuji-clinic-management-app.firebaseapp.com',
    storageBucket: 'fuji-clinic-management-app.appspot.com',
  );
}
